### ISSUE TITLE
Multisite Deploy

### ISSUE THREAD

**Issue by bradymwilliams** [PhilDL/remix-gospel-stack#20]
How would one go about adding a second remix site and deploying one or both on merge to main?

**Comment by PhilDL** [comment]
Hello, you didn't give me enough info, but let's say that you want both of the remix Apps to be deployed on fly.io with a Dockerfile.

Each app should have its own `fly.toml` and its `Dockerfile` inside its package. These 2 files should be modified accordingly, the `fly.toml` should have the correct name and the `Dockerfile` should be updated so all the commands like `RUN turbo prune --scope=remix-app --docker` should use the correct name of the second remix app instead of `remix-app`. 

Then you would handle everything in the GitHub workflow in `.github/workflows/deploy.yml`.
For example something like that:

```yml
  build:
    name: 🐳 Build
    # only build/deploy main branch on pushes
    if: ${{ (github.ref == 'refs/heads/main' || github.ref == 'refs/heads/dev') && github.event_name == 'push' }}
    runs-on: ubuntu-latest
    steps:
      - name: 🛑 Cancel Previous Runs
        uses: styfle/cancel-workflow-action@0.11.0

      - name: ⬇️ Checkout repo
        uses: actions/checkout@v3

      - name: 👀 Read remix APP 1 name
        uses: SebRollen/toml-action@v1.0.2
        id: app_1_name
        with:
          file: "apps/remix-app/fly.toml"
          field: "app"

      - name: 👀 Read remix APP 2 name
        uses: SebRollen/toml-action@v1.0.2
        id: app_2_name
        with:
          file: "apps/another-remix-app/fly.toml"
          field: "app"

      - name: 🐳 Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
        with:
          version: v0.9.1

      # Setup cache
      - name: ⚡️ Cache Docker layers
        uses: actions/cache@v3
        with:
          path: /tmp/.buildx-cache
          key: ${{ runner.os }}-buildx-${{ github.sha }}
          restore-keys: |
            ${{ runner.os }}-buildx-

      - name: 🔑 Fly Registry Auth
        uses: docker/login-action@v2
        with:
          registry: registry.fly.io
          username: x
          password: ${{ secrets.FLY_API_TOKEN }}

      - name: 🐳 Docker build APP 1
        uses: docker/build-push-action@v4
        with:
          context: .
          file: apps/remix-app/Dockerfile
          push: true
          tags: registry.fly.io/${{ steps.app_name.outputs.value }}:${{ github.ref_name }}-${{ github.sha }}
          build-args: |
            COMMIT_SHA=${{ github.sha }}
          cache-from: type=local,src=/tmp/.buildx-cache
          cache-to: type=local,mode=max,dest=/tmp/.buildx-cache-new

      - name: 🐳 Docker build APP 2
        uses: docker/build-push-action@v4
        with:
          context: .
          file: apps/another-remix-app/Dockerfile
          push: true
          tags: registry.fly.io/${{ steps.app_2_name.outputs.value }}:${{ github.ref_name }}-${{ github.sha }}
          build-args: |
            COMMIT_SHA=${{ github.sha }}
          cache-from: type=local,src=/tmp/.buildx-cache
          cache-to: type=local,mode=max,dest=/tmp/.buildx-cache-new

      # This ugly bit is necessary if you don't want your cache to grow forever
      # till it hits GitHub's limit of 5GB.
      # Temp fix
      # https://github.com/docker/build-push-action/issues/252
      # https://github.com/moby/buildkit/issues/1896
      - name: 🚚 Move cache
        run: |
          rm -rf /tmp/.buildx-cache
          mv /tmp/.buildx-cache-new /tmp/.buildx-cache
  deploy:
    name: 🚀 Deploy
    runs-on: ubuntu-latest
    needs: [lint, typecheck, vitest, cypress, build]
    # only build/deploy main branch on pushes
    if: ${{ (github.ref == 'refs/heads/main' || github.ref == 'refs/heads/dev') && github.event_name == 'push' }}

    steps:
      - name: 🛑 Cancel Previous Runs
        uses: styfle/cancel-workflow-action@0.11.0

      - name: ⬇️ Checkout repo
        uses: actions/checkout@v3

      - name: 👀 Read app name
        uses: SebRollen/toml-action@v1.0.2
        id: app_name
        with:
          file: "apps/remix-app/fly.toml"
          field: "app"

      - name: 🚀 Deploy Staging
        if: ${{ github.ref == 'refs/heads/dev' }}
        uses: superfly/flyctl-actions@1.3
        with:
          args: "deploy --app ${{ steps.app_name.outputs.value }}-staging --config ./apps/remix-app/fly.toml --image registry.fly.io/${{ steps.app_name.outputs.value }}:${{ github.ref_name }}-${{ github.sha }}"
        env:
          FLY_API_TOKEN: ${{ secrets.FLY_API_TOKEN }}

      - name: 🚀 Deploy Production
        if: ${{ github.ref == 'refs/heads/main' }}
        uses: superfly/flyctl-actions@1.3
        with:
          args: "deploy --config ./apps/remix-app/fly.toml --image registry.fly.io/${{ steps.app_name.outputs.value }}:${{ github.ref_name }}-${{ github.sha }}"
        env:
          FLY_API_TOKEN: ${{ secrets.FLY_API_TOKEN }}
```

I did not test exactly this code I just gave you, there may be some tweaking to be done but this is a general idea.
